name: manage-azure-policy-8c6e4015
on:
  workflow_dispatch:
    inputs:
      remarks:
        description: 'Reason for triggering the workflow run'
        required: false
        default: 'Updating Azure Policies'


## Uncomment the following if you wish to automatically trigger workflow run with every commit
#
#  push:
#    paths:
#      - 'AzPolicy/policies/LimitVMSize_a0f3d4fb-838b-4384-877f-4e01cd4d2609/**'
#      - 'AzPolicy/policies/Add_rule_to_NSGs_d7e13a94-01d8-42a7-b1ae-c272d2668f86/**'
#      - 'AzPolicy/policies/Audit_virtual_machines_without_disaster_recovery_configured_0015ea4d-51ff-4ce3-8d8c-f3f8f0179a56/**'
#      - 'AzPolicy/policies/Azure_Backup_should_be_enabled_for_Virtual_Machines_013e242c-8828-4970-87b3-ab247555486d/**'
#      - .github/workflows/manage-azure-policy-8c6e4015.yml
jobs:
  apply-azure-policy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS_8c6e4015}}
        allow-no-subscriptions: true
    - name: Create or Update Azure Policies
      uses: azure/manage-azure-policy@v0
      with:
        paths: |
          AzPolicy/policies/LimitVMSize_a0f3d4fb-838b-4384-877f-4e01cd4d2609/**
          AzPolicy/policies/Add_rule_to_NSGs_d7e13a94-01d8-42a7-b1ae-c272d2668f86/**
          AzPolicy/policies/Audit_virtual_machines_without_disaster_recovery_configured_0015ea4d-51ff-4ce3-8d8c-f3f8f0179a56/**
          AzPolicy/policies/Azure_Backup_should_be_enabled_for_Virtual_Machines_013e242c-8828-4970-87b3-ab247555486d/**
